# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'un.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        mainWindow.setMinimumSize(QtCore.QSize(800, 600))
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        mainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_1.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_1.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout_2.addWidget(self.pushButton_1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_5.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_5.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_13.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_13.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_2.addWidget(self.pushButton_13)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_8.addWidget(self.pushButton_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_6.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_6.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_8.addWidget(self.pushButton_6)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_10.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_10.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_8.addWidget(self.pushButton_10)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_14.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_14.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_8.addWidget(self.pushButton_14)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_3.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_9.addWidget(self.pushButton_3)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_9.addWidget(self.pushButton_7)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_11.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_11.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_9.addWidget(self.pushButton_11)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_15.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_15.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_9.addWidget(self.pushButton_15)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_4.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_4.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_10.addWidget(self.pushButton_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_8.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_8.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_10.addWidget(self.pushButton_8)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_12.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_12.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_10.addWidget(self.pushButton_12)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_16.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_16.setStyleSheet('''
                            background-image: url(sky.png);
                            border-radius: 20px;
                            color: #4700c2 ;
                        ''')
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_10.addWidget(self.pushButton_16)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        mainWindow.setStyleSheet('''
                            background-color: #afdafc;
                        ''')

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_1.setText(_translate("mainWindow", "1"))
        self.pushButton_5.setText(_translate("mainWindow", "5"))
        self.pushButton_9.setText(_translate("mainWindow", "9"))
        self.pushButton_13.setText(_translate("mainWindow", "13"))
        self.pushButton_2.setText(_translate("mainWindow", "2"))
        self.pushButton_6.setText(_translate("mainWindow", "6"))
        self.pushButton_10.setText(_translate("mainWindow", "10"))
        self.pushButton_14.setText(_translate("mainWindow", "14"))
        self.pushButton_3.setText(_translate("mainWindow", "3"))
        self.pushButton_7.setText(_translate("mainWindow", "7"))
        self.pushButton_11.setText(_translate("mainWindow", "11"))
        self.pushButton_15.setText(_translate("mainWindow", "15"))
        self.pushButton_4.setText(_translate("mainWindow", "4"))
        self.pushButton_8.setText(_translate("mainWindow", "8"))
        self.pushButton_12.setText(_translate("mainWindow", "12"))
        self.pushButton_16.setText(_translate("mainWindow", "16"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
